In [1]:
# Impoting Library
import selenium
from selenium import webdriver
import time
import requests
from selenium.common.exceptions import NoSuchElementException
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
#Setting connection to WebDriver
driver = webdriver.Chrome(r'C:\Users\RAJVEER\Downloads\chromedriver_win32\chromedriver.exe')

In [3]:
driver = webdriver.Chrome('chromedriver.exe')

# Solution 1

In [52]:
url='https://www.amazon.in/'
driver.get(url)

In [53]:
value =input("Please enter the product to be search for")
print(f'you entered {value}')

Please enter the product to be search forlaptop
you entered laptop

In [54]:
search_product = driver.find_element_by_class_name('nav-input')
search_product.send_keys(value)

In [55]:
Search_button = driver.find_element_by_xpath('/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div')
Search_button.click()

# Solution 2

In [58]:
page=requests.get("https://www.amazon.in/s?k="+value+"&ref=nb_sb_noss")

In [59]:
#fetch url for 3 pages if present
urls=[]
start=0
end=3

for page in range(start,end):
    time.sleep(4)
    for i in driver.find_elements_by_xpath('//a[@class="a-link-normal s-link-style a-text-normal"]'):
        urls.append(i.get_attribute("href"))
    nxt_button = driver.find_elements_by_xpath('//a[@class="s-pagination-item s-pagination-next s-pagination-button s-pagination-separator"]')
    try:
        driver.get(nxt_button[1].get_attribute('href'))
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [60]:
len(urls)

69

In [61]:
#define variable
brand_name =[]
product_name=[]
price_detail=[]
return_exchange=[]
expected_delivery=[]
availibility=[]

In [62]:
for i in urls:
    driver.get(i)
    time.sleep(2)
    
    #fectch brand name
    
    try:
        brand=driver.find_element_by_xpath('//span[@id="productTitle"]')
        brand_name.append(brand.text.split(" ")[0])
    except:
        brand_name.append('-')
        
    #fectch product name
    try:
        product=driver.find_element_by_xpath('//span[@id="productTitle"]')
        product_name.append(product.text)
    except:
        product_name.append('-')
        
    #fectch price details
    try:
        price=driver.find_element_by_xpath('//span[@id="tp_price_block_total_price_ww"]/span')
        price_detail.append(price.get_attribute('innerHTML'))
    except:
        price_detail.append('-')
        
     #fectch return/exchange
    try:
        rerurn=driver.find_element_by_xpath('//div[@class="a-section a-spacing-none icon-content"]/a')
        return_exchange.append(rerurn.text)
    except:
        return_exchange.append('-')
        
    #fectch expected delivery time
    try:
        delivery=driver.find_element_by_xpath('//div[@class="a-section a-spacing-mini"]/b')
        expected_delivery.append(delivery.text)
    except:
        expected_delivery.append('-')
        
    #fectch Availibility
    try:
        available=  driver.find_element_by_xpath('//span[@class="a-size-medium a-color-success"]')
        availibility.append(available.text)
    except:
        availibility.append('-')

In [63]:
print(len(urls))
print(len(brand_name))
print(len(product_name))
print(len(price_detail))
print(len(return_exchange))
print(len(expected_delivery))
print(len(availibility))

69
69
69
69
69
69
69

In [64]:
products = pd.DataFrame()
products['Brand Name']= brand_name
products['Product Nam']= product_name
products['Price']= price_detail
products['Return/Exchange']= return_exchange
products['Expected Delivery']= expected_delivery
products['Availibility']= availibility
products['URL']= urls
products

,Brand Name,Product Nam,Price,Return/Exchange,Expected Delivery,Availibility,URL
0,Lenovo,Lenovo Ideapad Gaming 3 AMD Ryzen 7 5800H 15.6...,"₹74,990.00",7 Days Replacement,"Monday, Jan 31",In stock.,https://www.amazon.in/gp/slredirect/picassoRed...
1,Lenovo,Lenovo Legion 5 AMD Ryzen 5 4600H 15.6 inch (3...,"₹65,990.00",7 Days Replacement,"Friday, Jan 28",In stock.,https://www.amazon.in/gp/slredirect/picassoRed...
2,Lenovo,"Lenovo Chromebook 14e 14.0"" FHD Business Lapto...","₹20,990.00",Pay on Delivery,"Friday, Jan 28",In stock.,https://www.amazon.in/Lenovo-Chromebook-Busine...
3,AVITA,AVITA Cosmos 2 in 1 Intel Celeron Dual Core 11...,"₹16,900.00",Pay on Delivery,"Monday, Jan 31",In stock.,https://www.amazon.in/AVITA-Celeron-Storage-NS...
4,HP,HP Chromebook 14 Intel Celeron N4020-4GB SDRAM...,"₹27,390.00",Pay on Delivery,"Friday, Jan 28",In stock.,https://www.amazon.in/HP-Chromebook-14a-na0003...
...,...,...,...,...,...,...,...
64,HP,HP 15 (2021) Thin & Light 10th Gen Intel Core ...,"₹41,990.00",7 Days Replacement,"Monday, Jan 31",In stock.,https://www.amazon.in/HP-Laptop-inches-Windows...
65,ASUS,"ASUS VivoBook 14 (2021), Intel Core i3-1115G4 ...","₹39,990.00",7 Days Replacement,"Monday, Jan 31",In stock.,https://www.amazon.in/ASUS-VivoBook-i3-1115G4-...
66,Dell,"Dell New 14 i5-11320H, 16GB, 512Gb SSD, Win 11...","₹65,990.00",7 Days Replacement,"Monday, Jan 31",In stock.,https://www.amazon.in/Dell-Integrated-Inspiron...
67,Dell,"Dell 15 (2021) Intel i3-1005G1 Laptop, 8GB, 1T...","₹41,940.00",7 Days Replacement,"Monday, Jan 31",Only 1 left in stock.,https://www.amazon.in/gp/slredirect/picassoRed...
68,ASUS,"ASUS VivoBook 14 (2021), 14-inch (35.56 cms) F...","₹59,990.00",7 Days Replacement,"Monday, Jan 31",In stock.,https://www.amazon.in/gp/slredirect/picassoRed...

In [66]:
products.to_csv('Amazon_product_serched.csv', index=False)

# Solution3

In [ ]:
url='https://images.google.com/'
driver.get(url)

In [140]:
value = ["fruits", "cars","Machine Learning", "Guitar", "Cakes"]
image_url =[]

In [141]:
for keyword in value:
    search_keyword = driver.find_element_by_xpath('//input[@class="gLFyf gsfi"]')
    search_keyword.send_keys(keyword)
    Search_button = driver.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/button')
    Search_button.click()
    time.sleep(5)
    image=driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')
    for value in range(0,10):
        try:
            image_url.append(image[value].get_attribute("src"))
        except:
            image_url.append('-')
            
    url='https://images.google.com/'
    driver.get(url)

In [142]:
len(image_url)

50

In [152]:
image_data = pd.DataFrame()
image_data['Fruits']= image_url[1:10]
image_data['Cars']= image_url[11:20]
image_data['Machine Learning']= image_url[21:30]
image_data['Guitar']= image_url[31:40]
image_data['Cakes']= image_url[41:50]
image_data

,Fruits,Cars,Machine Learning,Guitar,Cakes
0,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
1,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
2,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
3,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
4,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
5,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
6,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
7,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
8,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."

In [153]:
image_data.to_csv('image_url.csv', index=False)

# Solution 4

In [123]:
url='https://www.flipkart.com/'
driver.get(url)

In [133]:
value =input("Please enter the product to be search for")
print(f'you entered {value}')

Please enter the product to be search forpixel 4A
you entered pixel 4A

In [134]:
search_product = driver.find_element_by_class_name('_3704LK')
search_product.send_keys(value)

In [135]:
Search_button = driver.find_element_by_xpath('/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/button')
Search_button.click()

In [136]:
#fetch url
urls=[]
for i in driver.find_elements_by_xpath('//a[@class="_1fQZEK"]'):
        urls.append(i.get_attribute("href"))

In [137]:
len(urls)

24

In [138]:
#define variable
brand_name =[]
product_name=[]
color_detail=[]
ram_details=[]
strorage_Rom_details=[]
primary_camera_details=[]
secondary_camera_details=[]
display_detail=[]
battery_cap=[]
price_details=[]

In [139]:
for i in urls:
    driver.get(i)
    time.sleep(2)
    
    #fectch brand name
    
    try:
        brand=driver.find_element_by_xpath('//span[@class="B_NuCI"]')
        brand_name.append(brand.text.split(" ")[0])
    except:
        brand_name.append('-')
        
    #fectch product name
    try:
        product=driver.find_element_by_xpath('//span[@class="B_NuCI"]')
        product_name.append(product.text)
    except:
        product_name.append('-')
                
    #fectch color details
    try:
        color=driver.find_elements_by_xpath('//li[@class="_21lJbe"]')
        for value in range(0,7):
            if(value == 3):
                color_detail.append(color[value].text)
    except:
        color_detail.append('-')
        
    #fectch ram/rom/camera details
    details=driver.find_elements_by_xpath('//li[@class="_21Ahn-"]')
    for value in range(0,len(details)):
        try:
            if(value == 0 and "|" in details[value].text):
                ram_details.append(details[value].text.split("|")[0])
        except:
            ram_details.append('-')
        
        #fectch rom details
        try:
            if(value == 0 and "|" in details[value].text):
                strorage_Rom_details.append(details[value].text.split("|")[1])
        except:
            strorage_Rom_details.append('-')
        
         #fectch front camera details
        try:
            if(value == 2 and "|" in details[value].text):
                primary_camera_details.append(details[value].text.split("|")[1])
            elif(value == 2):
                primary_camera_details.append('-')
        except:
            primary_camera_details.append('-')
            
        #fectch back camera details
        try:
            if(value == 2 and "|" in details[value].text):
                secondary_camera_details.append(details[value].text.split("|")[0])
            elif (value == 2):
                secondary_camera_details.append(details[value].text)
        except:
            secondary_camera_details.append('-')
            
        #fectch display details
        try:
            if(value == 1):
                display_detail.append(details[value].text)
        except:
            display_detail.append('-')
            
            
        #fectch front camera details
        try:
            if(value == 3):
                battery_cap.append(details[value].text)
            elif(len(details)<=3 and value == 2):
                battery_cap.append(details[value].text)
        except:
            battery_cap.append('-')
               
     #fectch price details
    try:
        price=driver.find_element_by_xpath('//div[@class="_30jeq3 _16Jk6d"]')
        price_details.append(price.get_attribute('innerHTML'))
    except:
        price_details.append('-')

In [140]:
print(len(urls))
print(len(brand_name))
print(len(product_name))
print(len(color_detail))
print(len(ram_details))
print(len(strorage_Rom_details))
print(len(primary_camera_details))
print(len(secondary_camera_details))
print(len(display_detail))
print(len(battery_cap))
print(len(price_details))

24
24
24
24
24
24
24
24
24
24
24

In [141]:
smartphone = pd.DataFrame()
smartphone['Brand Name']= brand_name
smartphone['Product Nam']= product_name
smartphone['Color']= color_detail
smartphone['Ram']= ram_details
smartphone['Storage Rom']= strorage_Rom_details
smartphone['Primary Camera']= primary_camera_details
smartphone['Secondary Camera']= secondary_camera_details
smartphone['Display']= display_detail
smartphone['Battry Capacity']= battery_cap
smartphone['Price']= price_details
smartphone['URL']= urls
smartphone

,Brand Name,Product Nam,Color,Ram,Storage Rom,Primary Camera,Secondary Camera,Display,Battry Capacity,Price,URL
0,Google,"Google Pixel 4a (Just Black, 128 GB) (6 GB RAM)",Just Black,6 GB RAM,128 GB ROM,8MP Front Camera,12.2MP Rear Camera,14.76 cm (5.81 inch) Full HD+ Display,3140 mAh Battery,"₹27,999",https://www.flipkart.com/google-pixel-4a-just-...
1,Tecno,"Tecno Spark 7T (Nebula Orange, 128 GB) (4 GB ...",Nebula Orange,4 GB RAM,128 GB ROM,8MP Front Camera,48MP Rear Camera,16.56 cm (6.52 inch) HD+ Display,6000 mAh Battery,"₹10,890",https://www.flipkart.com/tecno-spark-7t-nebula...
2,Redmi,"Redmi 9A Sport (Carbon Black, 32 GB) (2 GB RAM)",Carbon Black,2 GB RAM,32 GB ROM,5MP Front Camera,13MP Rear Camera,16.59 cm (6.53 inch) HD+ Display,5000 mAh Battery,"₹7,759",https://www.flipkart.com/redmi-9a-sport-carbon...
3,Redmi,"Redmi 9A (Nature Green, 32 GB) (2 GB RAM)",Nature Green,2 GB RAM,32 GB ROM,-,13MP Rear Camera,16.59 cm (6.53 inch) Full HD+ Display,5000 mAh Battery,"₹7,722",https://www.flipkart.com/redmi-9a-nature-green...
4,Redmi,"Redmi 9A (SeaBlue, 32 GB) (2 GB RAM)",SeaBlue,2 GB RAM,32 GB ROM,-,13MP Rear Camera,16.59 cm (6.53 inch) Full HD+ Display,5000 mAh Battery,"₹7,699",https://www.flipkart.com/redmi-9a-seablue-32-g...
5,Redmi,"Redmi 9A (Midnight Black, 32 GB) (2 GB RAM)",Midnight Black,2 GB RAM,32 GB ROM,-,13MP Rear Camera,16.59 cm (6.53 inch) Full HD+ Display,5000 mAh Battery,"₹7,724",https://www.flipkart.com/redmi-9a-midnight-bla...
6,Redmi,"Redmi 9A Sport (Metallic Blue, 32 GB) (3 GB RAM)",Metallic Blue,3 GB RAM,32 GB ROM,5MP Front Camera,13MP Rear Camera,16.59 cm (6.53 inch) HD+ Display,5000 mAh Battery,"₹8,598",https://www.flipkart.com/redmi-9a-sport-metall...
7,Redmi,"Redmi 9A Sport (Carbon Black, 32 GB) (3 GB RAM)",Carbon Black,3 GB RAM,32 GB ROM,5MP Front Camera,13MP Rear Camera,16.59 cm (6.53 inch) HD+ Display,5000 mAh Battery,"₹8,415",https://www.flipkart.com/redmi-9a-sport-carbon...
8,Redmi,"Redmi 9A Sport (Coral Green, 32 GB) (3 GB RAM)",Coral Green,3 GB RAM,32 GB ROM,5MP Front Camera,13MP Rear Camera,16.59 cm (6.53 inch) HD+ Display,5000 mAh Battery,"₹8,427",https://www.flipkart.com/redmi-9a-sport-coral-...
9,SAMSUNG,"SAMSUNG Galaxy M52 5G (Blazing Black, 128 GB) ...",Blazing Black,6 GB RAM,128 GB ROM,32MP Front Camera,64MP + 12MP + 5MP,17.02 cm (6.7 inch) Full HD+ Display,5000 mAh Battery,"₹26,993",https://www.flipkart.com/samsung-galaxy-m52-5g...
10,Tecno,"Tecno Spark 7 (Magnet Black, 32 GB) (2 GB RAM)",Magnet Black,2 GB RAM,32 GB ROM,8MP Front Camera,16MP Rear Camera,16.56 cm (6.52 inch) HD+ Display,6000 mAh Battery,"₹7,975",https://www.flipkart.com/tecno-spark-7-magnet-...
11,Redmi,"Redmi 9 (Sky Blue, 64 GB) (4 GB RAM)",Sky Blue,4 GB RAM,64 GB ROM,5MP Front Camera,13MP + 2MP,16.59 cm (6.53 inch) HD+ Display,5000 mAh Battery,"₹10,600",https://www.flipkart.com/redmi-9-sky-blue-64-g...
12,Nokia,"Nokia G20 (Dark Blue, 64 GB) (4 GB RAM)",Dark Blue,4 GB RAM,64 GB ROM,8MP Front Camera,48MP Rear Camera,16.51 cm (6.5 inch) HD+ Display,5050 mAh Battery,"₹13,499",https://www.flipkart.com/nokia-g20-dark-blue-6...
13,SAMSUNG,"SAMSUNG Galaxy A22 (Black, 128 GB) (6 GB RAM)",Black,6 GB RAM,128 GB ROM,13MP Front Camera,48MP Rear Camera,16.26 cm (6.4 inch) HD+ Display,5000 mAh Battery,"₹17,635",https://www.flipkart.com/samsung-galaxy-a22-bl...
14,Redmi,"Redmi 9A Sport (Coral Green, 32 GB) (2 GB RAM)",Coral Green,2 GB RAM,32 GB ROM,5MP Front Camera,13MP Rear Camera,16.59 cm (6.53 inch) HD+ Display,5000 mAh Battery,"₹7,999",https://www.flipkart.com/redmi-9a-sport-coral-...
15,SAMSUNG,"SAMSUNG Galaxy M52 5G (Icy Blue, 128 GB) (6 G...",Icy Blue,6 GB RAM,128 GB ROM,32MP Front Camera,64MP + 12MP + 5MP,17.02 cm (6.7 inch) Full HD+ Display,5000 mAh Battery,"₹25,890",https://www.flipkart.com/samsung-galaxy-m52-5g...
16,Tecno,"Tecno Spark Go 2021 (Galaxy Blue, 32 GB) (2 G...",Galaxy Blue,2 GB RAM,32 GB ROM,8MP Front Camera,13MP Rear Camera,16.56 cm (6.52 inch) HD+ Display,5000 mAh Battery,"₹7,599",https://www.flipkart.com/tecno-spark-go-2021-g...
17,REDMI,"REDMI Note 10 Pro (Glacial Blue, 128 GB) (6 G...",Glacial Blue,6 GB RAM,128 GB ROM,-,64MP Rear Camera,16.94 cm (6.67 inch) Display,5020 mAh Battery,"₹19,990",https://www.flipkart.com/redmi-note-10-pro-gla...
18,REDMI,"REDMI 10 Prime (Phantom Black, 64 GB) (4 GB RAM)",Phantom Black,4 GB RAM,64 GB ROM,8MP Front Camera,50MP + 8MP + 2MP + 2MP,16.51 cm (6.5 inch) Full HD Display,6000 mAh Battery,"₹13,999",https://www.flipkart.com/redmi-10-prime-phanto...
19,Itel,"Itel A25 (Gradation Blue, 16 GB) (1 GB RAM)",Gradation Blue,1 GB RAM,16 GB ROM,2MP Front Camera,5MP Rear Camera,12.7 cm (5 inch) HD Display,3020 mAh Battery,"₹4,885",https://www.flipkart.com/itel-a25-gradation-bl...
20,Itel,"Itel A25 (Gradation Purple, 16 GB) (1 GB RAM)",Gradation Purple,1 GB RAM,16 GB ROM,2MP Front Camera,5MP Rear Camera,12.7 cm (5 inch) HD Display,3020 mAh Battery,"₹4,899",https://www.flipkart.com/itel-a25-gradation-pu...
21,REDMI,"REDMI 9 Power (Mighty Black, 64 GB) (4 GB RAM)",Mighty Black,4 GB RAM,64 GB ROM,8MP Front Camera,48MP + 8MP + 2MP + 2MP,16.59 cm (6.53 inch) Full HD+ Display,6000 mAh Battery,"₹13,999",https://www.flipkart.com/redmi-9-power-mighty-...
22,Nokia,Nokia 125 DS (Black),Black,4 MB RAM,4 MB ROM,-,1020 mAh Battery,6.1 cm (2.4 inch) Display,1020 mAh Battery,"₹2,199",https://www.flipkart.com/nokia-125-ds/p/itm3f3...
23,Itel,Itel it5026 (Blue),Blue,4 MB RAM,4 MB ROM,-,2MP Rear Camera,6.1 cm (2.4 inch) Display,1200 mAh Battery,"₹1,329",https://www.flipkart.com/itel-it5026/p/itm2d63...

In [142]:
smartphone.to_csv('smartphone.csv', index=False)

# Solution 5

In [149]:
url='https://www.google.co.in/maps'
driver.get(url)

In [170]:
value =input("Please enter the city name")
print(f'you entered {value}')

Please enter the city nameMeerut
you entered Meerut

In [171]:
search_product = driver.find_element_by_class_name('tactile-searchbox-input')
search_product.send_keys(value)

In [172]:
Search_button = driver.find_element_by_xpath('/html/body/div[3]/div[9]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/button')
Search_button.click()

In [173]:
url =driver.current_url
url

'https://www.google.co.in/maps/place/Meerut,+Uttar+Pradesh/@28.9872441,77.6289197,12z/data=!3m1!4b1!4m5!3m4!1s0x390c64f457b66325:0x42faa83387a6be5e!8m2!3d28.9844618!4d77.7064137'

In [174]:
values=[]
long=[]
lati=[]
values = url.split("@")[1].split(",")
long.append(values[0])
lati.append(values[1])

In [175]:
data = pd.DataFrame()
data['longitute']= long
data['latitute']= lati
data

    longitute    latitute
0  28.9872441  77.6289197

# Solution 6

In [179]:
url='https://trak.in/'
driver.get(url)

In [180]:
Search_button = driver.find_element_by_xpath('/html/body/div[1]/header/div[2]/div/div/div/div/nav/ul/li[9]/a')
Search_button.click()

In [183]:
#fectch deals data
deal_March=driver.find_elements_by_xpath('//table[@class="tablepress tablepress-id-56 dataTable no-footer"]/tbody/tr/td')

In [187]:
#define variable
date=[]
start_up_Name =[]
industry=[]
sub_verticle=[]
city=[]
investors_name=[]
investment_type=[]
amount=[]

In [190]:
start=0
end=9
for deals in range(0,5):
    for index in range(start,end):
        if(index == start+1):
            date.append(deal_March[index].text)

In [189]:
for deals in deal_March:
    date.append(deals.text)

# Solution 7

In [4]:
url='https://www.digit.in/'
driver.get(url)

In [5]:
Search_button = driver.find_element_by_xpath('/html/body/div[2]/div/div[4]/ul/li[3]/a')
Search_button.click()

In [6]:
Search_button = driver.find_element_by_xpath('/html/body/div[7]/div/div[2]/div[2]/ul/li[10]/a')
Search_button.click()

In [62]:
laptop_name=[]

In [63]:
#fectch deals data
fetch_data=driver.find_elements_by_xpath('//*[contains(@class,"TopNumbeHeading sticky-footer")]')
for data in fetch_data:
    laptop_name.append(data.text.replace("\n","").split(".")[1])

In [52]:
OS=[]
fetch_data_detail=driver.find_elements_by_xpath('//div[@class="Spcs-details"]/table/tbody/tr/td[3]')
start=0
end=1
for data in range(0,10):
    for data in range(start,end):
        OS.append(fetch_data_detail[data].text)
        if(start==21):
            start=start+8
            end= start+1
        else:
            start=start+7
            end= start+1

In [53]:
display=[]
start=1
end=2
for data in range(0,10):
    for data in range(start,end):
        display.append(fetch_data_detail[data].text)
        if(start==22):
            start=start+8
            end= start+1
        else:
            start=start+7
            end= start+1

In [54]:
processor=[]
start=2
end=3
for data in range(0,10):
    for data in range(start,end):
        processor.append(fetch_data_detail[data].text)
        if(start==23):
            start=start+8
            end= start+1
        else:
            start=start+7
            end= start+1

In [55]:
memory=[]
start=3
end=4
for data in range(0,10):
    for data in range(start,end):
        memory.append(fetch_data_detail[data].text)
        if(start==24):
            start=start+8
            end= start+1
        else:
            start=start+7
            end= start+1

In [56]:
weight=[]
start=4
end=5
for data in range(0,10):
    for data in range(start,end):
        weight.append(fetch_data_detail[data].text)
        if(start==25):
            start=start+8
            end= start+1
        else:
            start=start+7
            end= start+1

In [57]:
dimention=[]
start=5
end=6
for data in range(0,10):
    for data in range(start,end):
        dimention.append(fetch_data_detail[data].text)
        if(start==26):
            start=start+8
            end= start+1
        else:
            start=start+7
            end= start+1

In [58]:
g_processor=[]
start=6
end=7
for data in range(0,10):
    for data in range(start,end):
        g_processor.append(fetch_data_detail[data].text)
        if(start==27):
            start=start+8
            end= start+1
        else:
            start=start+7
            end= start+1

In [64]:
print(len(laptop_name))
print(len(OS))
print(len(display))
print(len(processor))
print(len(memory))
print(len(weight))
print(len(dimention))
print(len(g_processor))

10
10
10
10
10
10
10
10

In [65]:
data = pd.DataFrame()
data['Laptop Name']= laptop_name
data['OS']= OS
data['Display']= display
data['Processor']= processor
data['Memory']= memory
data['Weight']= weight
data['Dimension']= dimention
data['Graphic Processor']= g_processor
data

,Laptop Name,OS,Display,Processor,Memory,Weight,Dimension,Graphic Processor
0,ACER NITRO 5,Windows 10,"15.6"" (1920 x 1080)",AMD Ryzen 9 Octa Core | 2.4 GHz,1 TB HDD/16 GBGB DDR4,2.4,363.4 x 255 x 23.9,NVIDIA GeForce RTX 3070
1,MSI STEALTH 15M,Windows 10,"15.6"" (1920 x 1080)",Intel Core i7 11th Gen - 11375H | NA,1 TB SSD/16 GBGB DDR4,1.7,358.3 x 248 x 16.15,NVIDIA GeForce RTX 3060
2,ASUS ROG STRIX SCAR 15,Windows 10,"15.6"" (2560 x 1440)",AMD Ryzen 9 Octa Core - 5900HX | 3.3 GHz,2 TB SSD/32 GBGB DDR4,2.30,354 x 259 x 22.6,NVIDIA GeForce RTX 3080
3,ALIENWARE AREA 51M R2,Windows 10 Home,"17.3"" (1920 x 1080)",10th Gen Intel® Core™ i7-10700 | 2.90 GHz,1 TB SSD/16 GBGB DDR4,4.1,27.65 x 402.6 x 319.14,Intel® UHD Graphics 630
4,ALIENWARE M15 R3,Windows 10 Home,"15.6"" (3840 x 2160)",10th Gen Intel® Core™ i9-10980HK | NA,1 TB SSD/16 GBGB DDR4,NA,NA,NA
5,ASUS ROG STRIX SCAR 15,Windows 10 Home,"15.6"" (1920 x 1080)",AMD Ryzen™ 9 5900HX | 3.3 GHz,1 TB SSD/16 GBGB DDR4,2.30,35.4 x 25.9 x 2.26,NVIDIA® GeForce RTX™ 3070
6,ASUS ZEPHYRUS G14,Windows 10 Home,"14"" (1920 x 1080)",AMD 3rd Gen Ryzen 9 | 3.3 GHz,1 TB SSD/16 GBGB DDR4,1.65,32.5 x 22.1 x 1.8,NVIDIA GeForce RTX 2060
7,LENOVO LEGION 5I,Windows 10 Pro,"15.6"" (1920 x 1080)",10th Gen Intel® Core™ i5-10300H | 2.50 GHz,1 TB SSD/16 GBGB DDR4,2.3,363.06 x 259.61 x 23.57,NVIDIA® GeForce® GTX 1650 4GB
8,ASUS ROG ZEPHYRUS DUO 15,Windows 10,"15.6"" (3840 x 1100)",Intel Core i7 10th Gen 10875H | NA,512 GB SSD/4 GBGB DDR4,2.4,268.30 x 360.00 x 20.90,NVIDIA GeForce RTX 2070 Max-Q
9,ACER ASPIRE 7 GAMING LAPTOP,Windows 10 Home,"15.6"" (1920 x 1080)",AMD Ryzen™ 5-5500U hexa-core | NA,512 GB SSD/8 GBGB DDR4,2.15,2.29 x 36.3 x 25.4,NVIDIA® GeForce® GTX 1650

# Solution 8

In [69]:
url='https://www.forbes.com/billionaires/'
driver.get(url)

In [81]:
rank=[]
name=[]
net_worth=[]
age=[]
citizenship=[]
source=[]
industry=[]

In [82]:
rank_detail=driver.find_elements_by_xpath('//div[@class="rank"]')
for data in rank_detail:
    rank.append(data.text) 

len(rank)

200

In [83]:
name_detail=driver.find_elements_by_xpath('//div[@class="personName"]')
for data in name_detail:
    name.append(data.text) 

len(name)

200

In [84]:
net_worth_detail=driver.find_elements_by_xpath('//div[@class="netWorth"]')
for data in net_worth_detail:
    net_worth.append(data.text) 

len(net_worth)

200

In [85]:
age_detail=driver.find_elements_by_xpath('//div[@class="age"]')
for data in age_detail:
    age.append(data.text) 

len(age)

200

In [86]:
citizenship_detail=driver.find_elements_by_xpath('//div[@class="countryOfCitizenship"]')
for data in citizenship_detail:
    citizenship.append(data.text) 

len(citizenship)

200

In [87]:
source_detail=driver.find_elements_by_xpath('//div[@class="source"]')
for data in source_detail:
    source.append(data.text) 

len(source_detail)

200

In [88]:
industry_detail=driver.find_elements_by_xpath('//div[@class="category"]')
for data in industry_detail:
    industry.append(data.text) 

len(industry)

200

In [90]:
data = pd.DataFrame()
data['Rank']= rank
data['Name']= name
data['Net Worth']= net_worth
data['Age']= age
data['Citizenship']= citizenship
data['Source']= source
data['Industry']= industry
data

,Rank,Name,Net Worth,Age,Citizenship,Source,Industry
0,1.,Jeff Bezos,$177 B,57,United States,Amazon,Technology
1,2.,Elon Musk,$151 B,49,United States,"Tesla, SpaceX",Automotive
2,3.,Bernard Arnault & family,$150 B,72,France,LVMH,Fashion & Retail
3,4.,Bill Gates,$124 B,65,United States,Microsoft,Technology
4,5.,Mark Zuckerberg,$97 B,36,United States,Facebook,Technology
...,...,...,...,...,...,...,...
195,195.,Harry Triguboff,$11.2 B,88,Australia,real estate,Real Estate
196,197.,Leonid Fedun & family,$11.1 B,65,Russia,oil,Energy
197,197.,Eyal Ofer,$11.1 B,70,Israel,"real estate, shipping",Diversified
198,197.,Evan Spiegel,$11.1 B,30,United States,Snapchat,Technology
199,200.,Luis Carlos Sarmiento,$11 B,88,Colombia,banking,Finance & Investments

In [91]:
data.to_csv('billionaires.csv', index=False)

# Solution 9

In [95]:
url='https://www.youtube.com/watch?v=L7XF1zzNZfM'
driver.get(url)

In [106]:
comments=[]
comments_upvote=[]
time=[]

In [107]:
comments_detail=driver.find_elements_by_xpath('//yt-formatted-string[@class="style-scope ytd-comment-renderer"][2]')
for data in comments_detail:
    comments.append(data.text)
len(comments)

240

In [108]:
comments_upvote_detail=driver.find_elements_by_xpath('//span[@id="vote-count-middle"]')
for data in comments_upvote_detail:
    comments_upvote.append(data.text)

len(comments_upvote)

240

In [109]:
time_detail=driver.find_elements_by_xpath('//div[@id="header-author"]/yt-formatted-string/a')
for data in time_detail:
    time.append(data.text)
    
len(time)

240

In [111]:
data = pd.DataFrame()
data['Comments']= comments[0:200]
data['Comment UpVote']= comments_upvote[0:200]
data['Comment Time']= time[0:200]
data

,Comments,Comment UpVote,Comment Time
0,Michel:* being supportive *\nTanner: * freekin...,2K,1 year ago (edited)
1,It’s all fun and games till Luna starts breaki...,93,1 year ago
2,Matt teaches his daughter to throw Eggs on the...,414,1 year ago
3,Michael: Here’s Hailey \nTanner: OMG WHAT \nMa...,472,1 year ago
4,Omg the absolute PANIC in Tanner’s face when h...,758,1 year ago
...,...,...,...
195,Let’s be honest baby monkeys are ADORABLE I me...,2,1 year ago
196,That bao thing left me crying for 5 minutes. I...,,1 year ago
197,This episode they should’ve just made Luna as ...,,1 year ago
198,Tanner: I choose you \nMatt: Haley is it a dop...,6,1 year ago
199,Luna gets cuter & cuter,,1 year ago

# Solution 10

In [4]:
url='https://www.hostelworld.com/'
driver.get(url)

In [11]:
value =input("Please enter the product to be search for")
print(f'you entered {value}')

Please enter the product to be search forLondon,England
you entered London,England

In [14]:
search_product = driver.find_element_by_class_name('native-input')
search_product.send_keys(value)

In [15]:
Search_button = driver.find_element_by_xpath('/html/body/div[3]/div/div/div[1]/div/div[1]/div/div/div[1]/div/wds-search-dropdown/wds-search-list/wds-search-item[1]/div[2]')
Search_button.click()

In [16]:
Search_button = driver.find_element_by_xpath('/html/body/div[3]/div/div/div[1]/div/div[1]/div/div/div[1]/wds-search-form-double-l/div[2]/div[2]/wds-button/button')
Search_button.click()

In [17]:
hostel_name=[]
distance_from_city_centre=[]
ratings=[]
total_reviews=[]
overall_reviews=[]
privates_from_price=[]
dorms_from_price=[]
facilities=[]
property_description=[]

In [18]:
hostel=driver.find_elements_by_xpath('//h2[@class="title title-6"]')
for data in hostel:
    hostel_name.append(data.text) 

len(hostel_name)

30

In [19]:
distance=driver.find_elements_by_xpath('//a[@class="show-on-map"]')
for data in distance:
    distance_from_city_centre.append(data.text) 

len(distance_from_city_centre)

30

In [20]:
ratings_details=driver.find_elements_by_xpath('//div[@class="rating rating-summary-container big"]')
for data in ratings_details:
    ratings.append(data.text) 

len(ratings)

30

In [21]:
reviews=driver.find_elements_by_xpath('//div[@class="reviews"]')
for data in reviews:
    total_reviews.append(data.text) 

len(total_reviews)

30

In [22]:
over_reviews=driver.find_elements_by_xpath('//div[@class="keyword"]')
for data in over_reviews:
    overall_reviews.append(data.text) 

len(overall_reviews)

31

In [23]:
privates_price=driver.find_elements_by_xpath('//a[@class="prices"]/div[1]')
for data in privates_price:
    privates_from_price.append(data.text) 

len(privates_from_price)

31

In [24]:
dorms_price=driver.find_elements_by_xpath('//a[@class="prices"]/div[2]')
for data in dorms_price:
    try:
        dorms_from_price.append(data.text) 
    except:
        dorms_from_price.append("-") 
len(dorms_from_price)

30

In [25]:
facilities_detail=driver.find_elements_by_xpath('//div[@class="rating-factors prop-card-tablet rating-factors small"]')
for data in facilities_detail:
    facilities.append(data.text) 

len(facilities)

30

In [39]:
#fetch url
urls=[]
for i in driver.find_elements_by_xpath('//h2[@class="title title-6"]/a'):
        urls.append(i.get_attribute("href"))

In [40]:
for i in urls:
    driver.get(i)
    time.sleep(2)
    
    #fectch brand name
    
    try:
        description=driver.find_element_by_xpath('//div[@class="content collapse-content"][1]')
        property_description.append(description.text)
    except:
        property_description.append('-')

In [42]:
data = pd.DataFrame()
data['Hostel Name']= hostel_name
data['Distance From City Center']= distance_from_city_centre
data['Ratings']= ratings
data['Total Reviews']= total_reviews
data['Overall Reviews']= overall_reviews[1:31]
data['Privates From Price']= privates_from_price[1:31]
data['Dorms From Price']=dorms_from_price
data['Fcilities']= facilities
data['property description']= property_description
data

,Hostel Name,Distance From City Center,Ratings,Total Reviews,Overall Reviews,Privates From Price,Dorms From Price,Fcilities,property description
0,Mornington Camden,Hostel - 4.1km from city centre Show on Map,8.3\nFabulous\n44 Total Reviews,44 Total Reviews,Fabulous,No Privates Available,Dorms From\nRs3260,Perfect Location\nSuperb Staff\nFantastic Clea...,Mornington Camden Hostel is a high class spaci...
1,Smart Russell Square Hostel,Hostel - 2.6km from city centre Show on Map,6.7\nGood\n9567 Total Reviews,9567 Total Reviews,Good,Privates From\nRs3551,Dorms From\nRs1099,Perfect Location\nBrilliant Staff\nAwesome Cle...,"Nestled in the heart of London, walking distan..."
2,Smart Camden Inn Hostel,Hostel - 4.4km from city centre Show on Map,8.5\nFabulous\n2740 Total Reviews,2740 Total Reviews,Fabulous,No Privates Available,Dorms From\nRs1202,Perfect Location\nSuperb Staff\nFantastic Clea...,"Located in the middle of Camden Town, we’re th..."
3,Selina Camden,Hostel - 5.5km from city centre Show on Map,9.2\nSuperb\n15 Total Reviews,15 Total Reviews,Superb,Privates From\nRs11325,Dorms From\nRs3397.67 Rs2888,Perfect Location\nSuperb Staff\nFantastic Clea...,"Among underground music venues, innovative mus..."
4,Queen Elizabeth Chelsea,Hostel - 5.7km from city centre Show on Map,7.5\nVery Good\n3214 Total Reviews,3214 Total Reviews,Very Good,Privates From\nRs3382,Dorms From\nRs1403,Perfect Location\nSuperb Staff\nAwesome Cleanl...,PLEASE NOTE WE ONLY ACCEPT GUESTS FROM THE AGE...
5,Pickwick Hall,Hostel - 2.3km from city centre Show on Map,9.0\nSuperb\n2276 Total Reviews,2276 Total Reviews,Superb,Privates From\nRs8053,No Dorms Available,Perfect Location\nSuperb Staff\nFantastic Clea...,Pickwick Hall provides accommodation for touri...
6,New Cross Inn Hostel,Hostel - 6.1km from city centre Show on Map,7.4\nVery Good\n1055 Total Reviews,1055 Total Reviews,Very Good,Privates From\nRs4207.71 Rs3787,Dorms From\nRs1303.02 Rs1173,Wonderful Location\nMarvellous Staff\nAwesome ...,Welcome to New Cross Inn Hostel!\n\nA Friendly...
7,No.8 Willesden Hostel London,Hostel - 10km from city centre Show on Map,7.6\nVery Good\n4646 Total Reviews,4646 Total Reviews,Very Good,Privates From\nRs2679,Dorms From\nRs783,Wonderful Location\nSuperb Staff\nAwesome Clea...,At No.8 we take pride in our Customer Service ...
8,Safestay London Elephant & Castle,Hostel - 1.7km from city centre Show on Map,8.0\nFabulous\n4027 Total Reviews,4027 Total Reviews,Fabulous,Privates From\nRs5436,Dorms From\nRs1812,Perfect Location\nMarvellous Staff\nExcellent ...,Safestay at Elephant & Castle is ideal if you ...
9,Barmy Badger Backpackers,Hostel - 5.5km from city centre Show on Map,9.3\nSuperb\n1688 Total Reviews,1688 Total Reviews,Superb,Privates From\nRs6040,Dorms From\nRs2013,Perfect Location\nSuperb Staff\nFantastic Clea...,The Badger is unique for London in that we hav...
10,The London Home Hostel,Hostel - 8.2km from city centre Show on Map,3.9\nRating\n253 Total Reviews,253 Total Reviews,Rating,Privates From\nRs5536,No Dorms Available,,If you are looking to meet and socialise with ...
11,No.8 Seven Sisters,Hostel - 9km from city centre Show on Map,6.7\nGood\n3687 Total Reviews,3687 Total Reviews,Good,No Privates Available,Dorms From\nRs750,Wonderful Location\nMarvellous Staff,"For Great Facilities, Comfort & Affordability ..."
12,Burlington Residence,Hostel - 7.1km from city centre Show on Map,9.2\nSuperb\n33 Total Reviews,33 Total Reviews,Superb,No Privates Available,Dorms From\nRs2567,Perfect Location\nSuperb Staff\nFantastic Clea...,"Situated in South West London, close to Balham..."
13,Park Villa,Hostel - 6.3km from city centre Show on Map,8.3\nFabulous\n854 Total Reviews,854 Total Reviews,Fabulous,Privates From\nRs6164,Dorms From\nRs2215,Perfect Location\nSuperb Staff\nExcellent Clea...,Park Villa is a new boutique hostel in the hea...
14,Astor Hyde Park,Hostel - 4.3km from city centre Show on Map,8.4\nFabulous\n11386 Total Reviews,11386 Total Reviews,Fabulous,No Privates Available,Dorms From\nRs1510,Perfect Location\nSuperb Staff\nExcellent Clea...,Located in the most beautiful and charming nei...
15,Wombat's The City Hostel London,Hostel - 3.6km from city centre Show on Map,8.8\nFabulous\n13372 Total Reviews,13372 Total Reviews,Fabulous,Privates From\nRs8085.25 Rs6064,Dorms From\nRs2585.48 Rs1939,Perfect Location\nSuperb Staff\nFantastic Clea...,Wombat's The City Hostel London is definitely ...
16,St Christopher's Greenwich,Hostel - 7.6km from city centre Show on Map,7.1\nVery Good\n3155 Total Reviews,3155 Total Reviews,Very Good,Privates From\nRs4469.43 Rs4022,Dorms From\nRs1162.1 Rs1046,Wonderful Location\nMarvellous Staff\nAwesome ...,COVID 19 Policy Update.\nIn response to Corona...
17,St Christopher's Oasis-Female Only,Hostel - 1.8km from city centre Show on Map,7.9\nVery Good\n620 Total Reviews,620 Total Reviews,Very Good,Privates From\nRs4245.74 Rs3821,Dorms From\nRs1329.87 Rs1197,Perfect Location\nSuperb Staff\nExcellent Clea...,COVID 19 Policy Update.\nIn response to Corona...
18,St Christopher's Camden,Hostel - 4.3km from city centre Show on Map,7.2\nVery Good\n3731 Total Reviews,3731 Total Reviews,Very Good,Privates From\nRs5736.3 Rs5163,Dorms From\nRs1262.01 Rs1136,Perfect Location\nMarvellous Staff\nAwesome Cl...,COVID 19 Policy Update.\nIn response to Corona...
19,St Christopher's Shepherds Bush,Hostel - 7km from city centre Show on Map,8.3\nFabulous\n642 Total Reviews,642 Total Reviews,Fabulous,Privates From\nRs4245.74 Rs3821,Dorms From\nRs1218.02 Rs1096,Perfect Location\nSuperb Staff\nAwesome Cleanl...,COVID 19 Policy Update.\nIn response to Corona...
20,St Christopher's Hammersmith,Hostel - 7.5km from city centre Show on Map,7.6\nVery Good\n3972 Total Reviews,3972 Total Reviews,Very Good,No Privates Available,Dorms From\nRs1173.29 Rs1056,Perfect Location\nSuperb Staff\nExcellent Clea...,"In response to Coronavirus (COVID-19), additio..."
21,St Christopher's Inn - Liverpool Street,Hostel - 3.2km from city centre Show on Map,8.5\nFabulous\n374 Total Reviews,374 Total Reviews,Fabulous,No Privates Available,Dorms From\nRs1553.57 Rs1398,Perfect Location\nSuperb Staff\nFantastic Clea...,COVID 19 Policy Update.\nIn response to Corona...
22,St Christopher's Inn - London Bridge,Hostel - 1.8km from city centre Show on Map,8.1\nFabulous\n3255 Total Reviews,3255 Total Reviews,Fabulous,No Privates Available,Dorms From\nRs1396.98 Rs1257,Perfect Location\nSuperb Staff\nExcellent Clea...,COVID 19 Policy Update.\nIn response to Corona...
23,"PubLove @ The White Ferry, Victoria",Hostel - 2.4km from city centre Show on Map,8.4\nFabulous\n188 Total Reviews,188 Total Reviews,Fabulous,Privates From\nRs11476,Dorms From\nRs1577,Perfect Location\nSuperb Staff\nExcellent Clea...,"Walk to the river, turn left, and just keep wa..."
24,Smart Hyde Park Inn Hostel,Hostel - 5km from city centre Show on Map,6.8\nGood\n6261 Total Reviews,6261 Total Reviews,Good,Privates From\nRs4228,Dorms From\nRs1242,Perfect Location\nBrilliant Staff\nGood Cleanl...,"Hi everyone London visitor, I'm living at SMAR..."
25,Smart Hyde Park View Hostel,Hostel - 5km from city centre Show on Map,7.7\nVery Good\n4518 Total Reviews,4518 Total Reviews,Very Good,Privates From\nRs4939,Dorms From\nRs1362,Perfect Location\nSuperb Staff\nExcellent Clea...,"Everything was perfect...., very clean, perfec..."
26,Safestay London Kensington Holland Park,Hostel - 5.9km from city centre Show on Map,8.0\nFabulous\n1108 Total Reviews,1108 Total Reviews,Fabulous,Privates From\nRs5436,Dorms From\nRs1812,Perfect Location\nMarvellous Staff\nExcellent ...,Safestay Holland Park\n\nSafestay Holland Park...
27,Urbany Hostel London,Hostel - 5.4km from city centre Show on Map,9.6\nSuperb\n189 Total Reviews,189 Total Reviews,Superb,Privates From\nRs6628,Dorms From\nRs1704,Perfect Location\nSuperb Staff\nFantastic Clea...,"Welcome to Urbany Hostel London, our first int..."
28,Astor Kensington,Hostel - 4.9km from city centre Show on Map,7.3\nVery Good\n6341 Total Reviews,6341 Total Reviews,Very Good,Privates From\nRs5939,Dorms From\nRs1409,Perfect Location\nSuperb Staff,"Located a short walk from Notting Hill, Hyde P..."
29,Phoenix Hostel,Hostel - 4.2km from city centre Show on Map,7.8\nVery Good\n3481 Total Reviews,3481 Total Reviews,Very Good,Privates From\nRs2977.39 Rs2680,Dorms From\nRs1509.94 Rs1359,Perfect Location\nSuperb Staff\nExcellent Clea...,*Please note we are operating on LIMITED recep...